name: Android Release Build
on:
  push:
    branches: main
    tags:
      - v*
jobs:
  StoreLocalFiles:
    uses: BreakZero/TODO-LIST-KMM/.github/workflows/local-file-prepare.yml@main

  release_build:
    runs-on: macos-12
    if: startsWith(github.ref, 'refs/tags/')
    needs: StoreLocalFiles

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Store Local Files
        run: |
          mkdir keystore
          cd . > keystore/keystore.properties
          cd . > keystore/todo_keystore.jks
          echo ${{ secrets.SIGNING_STORE_PROPERTIES }} | base64 --decode > keystore/keystore.properties
          echo ${{ secrets.SIGNING_KEY_STORE_BASE64 }} | base64 --decode > keystore/todo_keystore.jks

      - name: Generate cache key
        run: ./scripts/checksum.sh . checksum.txt

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Release apk
        run: ./gradlew assembleRelease

      - name: Build Release bundle
        run: ./gradlew bundleRelease

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          paths: |
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab